# Generated by Django 3.2.3 on 2021-05-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('qn', models.TextField(default='')),
                ('a', models.CharField(max_length=500)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=10)),
                ('result', models.IntegerField(default=0)),
                ('sub', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('qn', models.TextField(default='')),
                ('a', models.CharField(max_length=500)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=10)),
                ('result', models.IntegerField(default=0)),
                ('sub', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
