# Generated by Django 3.2.3 on 2021-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_biology_chemistry_economics_maths_physics_politics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology',
            name='ans',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='ans',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='economics',
            name='ans',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='geography',
            name='ans',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='ans',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maths',
            name='ans',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='physics',
            name='ans',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='politics',
            name='ans',
            field=models.CharField(max_length=100),
        ),
    ]
